import Head from "next/head";
import Image from "next/image";
import AboutMe from "../components/AboutMe";
import CTA from "../components/CTA";
import Footer from "../components/Footer";
import Hero from "../components/Hero";
import Navbar from "../components/Navbar";
import Projects from "../components/Projects";
import Quote from "../components/Quote";
import SelectedProjects from "../components/SelectedProjects";
import Timeline from "../components/Timeline";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Jyotindra Tavanoji</title>
        <meta name="description" content="Generated by create next app" />

        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Navbar />
        <Hero />
        <Projects />
        <SelectedProjects />
        <Timeline />
        <Quote />
        <AboutMe />
        <CTA />
        <Footer />
      </main>
    </div>
  );
}
