import Head from 'next/head';
import Image from 'next/image';
import AboutMe from '../components/AboutMe';
import CTA from '../components/CTA';
import Footer from '../components/Footer';
import Hero from '../components/Hero';
import Navbar from '../components/Navbar';
import Projects from '../components/Projects';
import Quote from '../components/Quote';
import SelectedProjects from '../components/SelectedProjects';
import Timeline from '../components/Timeline';
import { TabsDemo } from '@/components/AnimatedTabs';
import { LampDemo } from '@/components/LampDemo';
import MaxWidthWrapper from '@/components/ui/max-width-wrapper';
import { Button } from '@/components/ui/button';
import { ArrowUpRight, GitCommitHorizontal, Twitter } from 'lucide-react';
import AccordionComponent from '@/components/Accordion';

export default function Home() {
  return (
    <div>
      <Head>
        <title>Jyotindra Tavanoji</title>
        <meta name='description' content='Generated by create next app' />

        <link rel='icon' href='/logo.png' />
      </Head>

      <main>
        <Navbar />
        <Hero />
        <Projects />
        <MaxWidthWrapper className='py-12'>
          <div className='mb-12 px-6 lg:px-8'>
            <div className='mx-auto max-w-2xl sm:text-center'>
              <h2 className='text-3xl order-1 mt-2 tracking-tight text-center text-balance !leading-tight font-bold md:text-5xl lg:text-6xl text-gray-900'>
                Checkout ʻfew of my{' '}
                <span className='relative px-2 bg-green-600 text-white'>
                  many projects
                </span>{' '}
                now.
              </h2>
              <div className='mt-12'>
                <Button className='rounded-full' onClick={() => {}}>
                  <ArrowUpRight className='mr-2 h-4 w-4 text-white' />
                  All my projects
                </Button>
              </div>
            </div>
          </div>
        </MaxWidthWrapper>
        <TabsDemo />
        <AboutMe />

        <Timeline />
        <Quote />
        <MaxWidthWrapper className='py-12 '>
          <div className='mb-12 px-6 lg:px-8'>
            <div className='mx-auto sm:text-center'>
              <h2 className='text-3xl order-1 mt-2 tracking-tight text-center text-balance !leading-tight font-bold md:text-5xl lg:text-6xl text-gray-900'>
                Not getting enough of me yet ? Dive into my{' '}
                <span className='relative text-gray-400'>github</span> profile
                right now, or lets chat on{' '}
                <span className='relative text-blue-400'>twitter</span> about
                your new product.
              </h2>
              <div className='mt-12 flex justify-center'>
                <Button
                  className='rounded-full text-lg bg-gray-400'
                  onClick={() => {}}
                >
                  <GitCommitHorizontal className='mr-2 h-4 w-4 text-white' />
                  Github Profile
                </Button>
                <Button
                  className='rounded-full ml-6 bg-blue-400 text-lg'
                  onClick={() => {}}
                >
                  <Twitter className='mr-2 h-4 w-4' />
                  Letʻs Connect
                </Button>
              </div>
            </div>
          </div>
        </MaxWidthWrapper>
        <CTA />
        <Footer />
      </main>
    </div>
  );
}
