import React from "react";
import Head from "next/head";
import Navbar from "../components/Navbar";
import ShowcaseProjects from "../components/ShowcaseProjects";
import CTA from "../components/CTA";
import Footer from "../components/Footer";

const Showcase = () => {
  return (
    <div>
      <Head>
        <title>Showcase Projects</title>
        <meta name="description" content="Generated by create next app" />

        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Navbar />
        <ShowcaseProjects />
        <CTA />
        <Footer />
      </main>
    </div>
  );
};

export default Showcase;
